Repository netbox-community/netbox-docker, pull requests merged in 2018-06, with the labels that each got.

#70 Update to Alpine 3.7
  Dockerfile
Labels: awaiting answer

#66 Fix for broken field filterable
  README.md
  VERSION
  initializers/custom_fields.yml
  startup_scripts/20_custom_fields.py
Labels: awaiting answer, bug

#55 Add support for auto_weight counter
  initializers/custom_fields.yml
  startup_scripts/20_custom_fields.py
Labels: awaiting answer, enhancement
