Repository netbox-community/netbox-docker, pull requests merged in 2019-11, with the labels that each got.

#182 A new issue category for feature/change requests
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: discussion

#191 Respect SKIP_GIT environment variable when building
  build.sh
Labels: bug

#187 Ignore local override file
  .gitignore
Labels: awaiting answer, enhancement

#185 Adds more labels to the Dockerfile
  .github/ISSUE_TEMPLATE/bug_report.md
  Dockerfile
  README.md
  build.sh
Labels: enhancement
