Repository netbox-community/netbox-docker, pull requests merged in 2019-12, with the labels that each got.

#189 Adds a link to the Getting Started wiki section to the README
  README.md
Labels: enhancement

#193 Revert "Fix #179 'libc not found'"
  Dockerfile
Labels: maintenance

#194 Update Redis to Version 5
  docker-compose.yml
Labels: maintenance

#177 Add SSLMODE to database connection settings
  configuration/configuration.py
Labels: awaiting answer, enhancement

#198 Remove use of GNU date extensions when labeling images
  build.sh
Labels: bug

#196 Add rack group initialiser
  initializers/rack_groups.yml
  initializers/racks.yml
  startup_scripts/075_rack_groups.py
Labels: enhancement

#204 Reduce the Docker Context
  .dockerignore
Labels: maintenance

#203 Pull Request Template Suggestion
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement

#207 Massive speedup in executing startup_scripts
  docker/docker-entrypoint.sh
  startup_scripts/__main__.py
Labels: enhancement

#206 Adds a test that validates the initializer yml files
  hooks/test
  test.sh
Labels: enhancement

#202 Prepares scripts and documentation for #184
  DOCKER_HUB.md
  README.md
  build-branches.sh
  build.sh
  hooks/common
  hooks/push
Labels: enhancement

#201 Fix variables for Dockerhub build
  hooks/common
Labels: bug

#195 Update PostgreSQL to 11
  docker-compose.yml
Labels: maintenance

#186 Non root
  Dockerfile
  docker-compose.yml
  docker/docker-entrypoint.sh
Labels: discussion, enhancement, help wanted
