Repository netbox-community/netbox-docker, pull requests merged in 2020-10, with the labels that each got.

#301 Add optional primary_ip on virtual machines initializer
  initializers/devices.yml
  initializers/virtual_machines.yml
  startup_scripts/130_devices.py
  startup_scripts/230_virtual_machines.py
  startup_scripts/270_primary_ips.py
Labels: enhancement

#327 add option to mirror ldap groups into netbox
  configuration/ldap_config.py
Labels: enhancement

#345 Enable Sponsoring Button
  .github/FUNDING.yml
Labels: maintenance

#310 Add REMOTE_AUTH_* configs
  configuration/configuration.py
Labels: discussion, enhancement

#343 Dynamic Configuration
  .gitignore
  Dockerfile
  configuration/configuration.py
  configuration/extra.py
  configuration/ldap/ldap_config.py
  docker/configuration.docker.py
  docker/gunicorn_config.py
  docker/ldap_config.docker.py
  startup_scripts/__main__.py
Labels: discussion, enhancement

#346 Fix warning in Github Actions
  build.sh
Labels: maintenance

#344 Prepare for Monitoring with Prometheus
  .gitignore
  README.md
  docker-compose.yml
  docker/gunicorn_config.py
  docker/nginx.conf
  env/netbox.env
Labels: enhancement

#347 Use release version of Python 3.9 in tests
  .github/workflows/push.yml
Labels: maintenance

#349 Version 0.26.0
  .github/FUNDING.yml
  .github/workflows/push.yml
  .gitignore
  Dockerfile
  README.md
  VERSION
  build.sh
  configuration/configuration.py
  configuration/extra.py
  configuration/ldap/ldap_config.py
  docker-compose.test.yml
  docker-compose.yml
  docker/configuration.docker.py
  docker/docker-entrypoint.sh
  docker/gunicorn_config.py
  docker/ldap_config.docker.py
  docker/nginx.conf
  env/netbox.env
  initializers/devices.yml
  initializers/sites.yml
  initializers/virtual_machines.yml
  startup_scripts/130_devices.py
  startup_scripts/230_virtual_machines.py
  startup_scripts/270_primary_ips.py
  startup_scripts/__main__.py
Labels: enhancement, maintenance

#350 Fix "'NoneType' object has no attribute 'lower'" when no AUTH_LDAP_MI…
  configuration/ldap/ldap_config.py
Labels: bug, hacktoberfest-accepted

#351 Revert changes to 'gunicorn_config.py'
  docker/gunicorn_config.py
Labels: bug

#353 Version 0.26.1
  VERSION
  configuration/ldap/ldap_config.py
  docker/gunicorn_config.py
Labels: maintenance

#354 Fix ldap configuration in /etc/netbox/config/ldap/*.py not loaded
  docker/ldap_config.docker.py
Labels: bug, hacktoberfest-accepted

#355 Version 0.26.2
  VERSION
  docker/ldap_config.docker.py
Labels: maintenance

#328 Allow disabling LDAP-group related settings when AUTH_LDAP_*_GROUP environment variables are not defined
  configuration/ldap/ldap_config.py
Labels: enhancement

#348 Upgrade Python image to 3.9-alpine
  .github/workflows/push.yml
  build.sh
Labels: hacktoberfest-accepted, maintenance
