Repository netbox-community/netbox-docker, pull requests merged in 2020-01, with the labels that each got.

#221 Improve test.sh
  .gitignore
  docker-compose.test.yml
  test.sh
Labels: maintenance

#222 Fix Github Action
  .github/workflows/push.yml
  .github/workflows/release.yml
  build-latest.sh
  build.sh
  test.sh
Labels: maintenance

#209 Prepare for Netbox 2.7
  Dockerfile
  configuration/configuration.py
  docker-compose.yml
  env/netbox.env
  env/redis-cache.env
  initializers/custom_fields.yml
  initializers/dcim_interfaces.yml
  initializers/devices.yml
  initializers/ip_addresses.yml
  initializers/prefixes.yml
  initializers/racks.yml
  initializers/virtual_machines.yml
  initializers/vlans.yml
  startup_scripts/020_custom_fields.py
  startup_scripts/080_racks.py
  startup_scripts/130_devices.py
  startup_scripts/210_vlans.py
  startup_scripts/220_prefixes.py
  startup_scripts/230_virtual_machines.py
  startup_scripts/250_dcim_interfaces.py
  startup_scripts/260_ip_addresses.py
Labels: maintenance

#218 Check that `develop` is the base branch in new PRs
  .github/pull_request_template.md
Labels: enhancement

#225 Prepare 0.21.0
  README.md
  VERSION
Labels: maintenance

#229 Readme Cleanup
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  .github/workflows/push.yml
  .github/workflows/release.yml
  DOCKER_HUB.md
  README.md
Labels: maintenance

#230 Preparation for 0.21.1
  VERSION
Labels: maintenance

#232 Release 0.21.1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  .github/workflows/push.yml
  .github/workflows/release.yml
  DOCKER_HUB.md
  README.md
  VERSION
Labels: maintenance

#234 Enable push workflow for PRs
  .github/workflows/push.yml
Labels: maintenance

#233 update ldap caching configuration
  configuration/ldap_config.py
Labels: bug
