Repository netbox-community/netbox-docker, pull requests merged in 2021-02, with the labels that each got.

#419 Version 1.0.1
  .github/workflows/push.yml
  VERSION
  docker/launch-netbox.sh
  requirements-container.txt
Labels: maintenance

#423 Change the phrasing of the alternative issue options
  .github/ISSUE_TEMPLATE/config.yml
Labels: maintenance

#421 Provide backends for django-storages in our images
  requirements-container.txt
Labels: enhancement

#425 NetBox should always be referred to as NetBox
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/push.yml
  .github/workflows/release.yml
  Dockerfile
  README.md
  build-next.sh
  build.sh
  docker/docker-entrypoint.sh
  test.sh
Labels: maintenance

#426 Dependencies to build 'cryptography' Python package
  Dockerfile
Labels: bug

#431 Move Documentation about Version to Wiki
  README.md
Labels: documentation

#444 Remove MicroBadger Badges
  README.md
Labels: maintenance

#450 Fix loading main_config again during discovery of dynamic configurations
  docker/configuration.docker.py
Labels: bug
