Repository netbox-community/netbox-docker, pull requests merged in 2021-04, with the labels that each got.

#482 Fixes #480: Custom Links initialiser breaks if content_type is invalid
  startup_scripts/280_custom_links.py
Labels: awaiting answer, bug

#492 Fix quoting of exec argument in the entrypoint script
  docker/docker-entrypoint.sh
Labels: bug

#485 Initializer updates for Netbox 2.11
  .github/workflows/push.yml
  initializers/custom_links.yml
  initializers/devices.yml
  initializers/locations.yml
  initializers/power_panels.yml
  initializers/racks.yml
  initializers/vlan_groups.yml
  startup_scripts/075_locations.py
  startup_scripts/080_racks.py
  startup_scripts/140_devices.py
  startup_scripts/145_devices.py
  startup_scripts/200_vlan_groups.py
  startup_scripts/330_power_panels.py
Labels: maintenance

#448 AUTH_LDAP_MIRROR_GROUPS ldap_config tweak
  .gitignore
  configuration/ldap/extra.py
Labels: awaiting answer, enhancement

#496 Plugins and logging
  .gitignore
  configuration/logging.py
  configuration/plugins.py
Labels: enhancement

#497 user, group, & permissions fix
  initializers/groups.yml
  initializers/object_permissions.yml
  initializers/users.yml
  startup_scripts/000_users.py
  startup_scripts/010_groups.py
  startup_scripts/015_object_permissions.py
  startup_scripts/startup_script_utils/__init__.py
  startup_scripts/startup_script_utils/permissions.py
Labels: bug

#498 Build feature branch
  .github/workflows/push.yml
  .github/workflows/release.yml
  build-next.sh
Labels: maintenance

#493 Release 1.2.0
  .github/workflows/push.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  VERSION
  build-next.sh
  configuration/ldap/extra.py
  configuration/logging.py
  configuration/plugins.py
  docker-compose.override.yml.example
  docker-compose.yml
  docker/docker-entrypoint.sh
  initializers/custom_links.yml
  initializers/devices.yml
  initializers/groups.yml
  initializers/locations.yml
  initializers/object_permissions.yml
  initializers/power_panels.yml
  initializers/racks.yml
  initializers/users.yml
  initializers/vlan_groups.yml
  requirements-container.txt
  startup_scripts/000_users.py
  startup_scripts/010_groups.py
  startup_scripts/015_object_permissions.py
  startup_scripts/075_locations.py
  startup_scripts/080_racks.py
  startup_scripts/140_devices.py
  startup_scripts/145_devices.py
  startup_scripts/200_vlan_groups.py
  startup_scripts/280_custom_links.py
  startup_scripts/330_power_panels.py
  startup_scripts/startup_script_utils/__init__.py
  startup_scripts/startup_script_utils/permissions.py
Labels: maintenance
