Repository netbox-community/netbox-docker, pull requests merged in 2021-01, with the labels that each got.

#386 Links for issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: maintenance

#361 Nginx unit
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/push.yml
  Dockerfile
  README.md
  build.sh
  docker-compose.test.yml
  docker-compose.yml
  docker/configuration.docker.py
  docker/docker-entrypoint.sh
  docker/gunicorn_config.py
  docker/launch-netbox.sh
  docker/nginx-unit.json
  docker/nginx.conf
  requirements-container.txt
  test.sh
Labels: enhancement

#393 Bugfix - Allow primary device IP without virtual machine initialization
  startup_scripts/270_primary_ips.py
Labels: awaiting answer, bug

#397 Skip Startup Scripts in Unit Tests
  docker-compose.test.yml
  test.sh
Labels: maintenance

#399 Prevent "alpine:edge" from failling the workflow
  .github/workflows/push.yml
Labels: maintenance

#398 Update of ruamel.yaml
  requirements-container.txt
Labels: maintenance

#413 Is greater than or equal to is "-ge" and not "-gte".
  docker/launch-netbox.sh
Labels: bug
