Repository netbox-community/netbox-docker, pull requests merged in 2022-10, with the labels that each got.

#852 Define a volume for the caching Redis
  docker-compose.yml
Labels: enhancement

#860 Improve Help for build.sh
  build.sh
Labels: maintenance

#857 Updates the configuration, changes default for dynamic paramters to None
  configuration/configuration.py
  env/netbox.env
Labels: bug, maintenance
